import type { NativeGlassStats } from '../../ExpoAdaptiveGlassModule';
import type { GlassDeviceInfo } from '../../types';

const base: GlassDeviceInfo = {
  platform: 'ios',
  osVersion: '26.0',
  apiLevel: 26,
  totalMemoryMB: 8192,
  lowRamDevice: false,
  cpuCores: 6,
  performanceClass: 0,
  screenWidth: 393,
  screenHeight: 852,
  screenScale: 3,
  maxRefreshRate: 120,
  supportsSystemGlass: true,
  supportsLiveBlur: true,
  supportsShader: false,
};

export const devices = {
  highEndIphone: base,
  olderIphone: {
    ...base,
    osVersion: '17.5',
    apiLevel: 17,
    totalMemoryMB: 3072,
    maxRefreshRate: 60,
    supportsSystemGlass: false,
  },
  highEndAndroid: {
    ...base,
    platform: 'android',
    osVersion: '15',
    apiLevel: 35,
    performanceClass: 34,
    screenWidth: 412,
    screenHeight: 915,
    supportsSystemGlass: false,
    supportsShader: true,
  },
  midAndroid: {
    ...base,
    platform: 'android',
    osVersion: '13',
    apiLevel: 33,
    totalMemoryMB: 4096,
    cpuCores: 8,
    maxRefreshRate: 90,
    screenWidth: 412,
    screenHeight: 915,
    supportsSystemGlass: false,
    supportsShader: true,
  },
  android12: {
    ...base,
    platform: 'android',
    osVersion: '12',
    apiLevel: 31,
    totalMemoryMB: 6144,
    cpuCores: 8,
    performanceClass: 31,
    screenWidth: 412,
    screenHeight: 915,
    supportsSystemGlass: false,
    supportsShader: false,
  },
  lowEndAndroid: {
    ...base,
    platform: 'android',
    osVersion: '11',
    apiLevel: 30,
    totalMemoryMB: 3072,
    cpuCores: 8,
    maxRefreshRate: 60,
    screenWidth: 360,
    screenHeight: 780,
    supportsSystemGlass: false,
    supportsLiveBlur: false,
    supportsShader: false,
  },
  lowRamAndroid: {
    ...base,
    platform: 'android',
    osVersion: '10',
    apiLevel: 29,
    totalMemoryMB: 2048,
    lowRamDevice: true,
    cpuCores: 4,
    maxRefreshRate: 60,
    screenWidth: 360,
    screenHeight: 780,
    supportsSystemGlass: false,
    supportsLiveBlur: false,
    supportsShader: false,
  },
} satisfies Record<string, GlassDeviceInfo>;

export function stats(over: Partial<NativeGlassStats> = {}): NativeGlassStats {
  return {
    windowMs: 500,
    sampleCount: 60,
    refreshRate: 120,
    targetFrameTimeMs: 8.33,
    averageFrameTimeMs: 8.4,
    worstFrameTimeMs: 9,
    droppedFrameRatio: 0,
    thermalState: 'nominal',
    lowPowerMode: false,
    lowMemory: false,
    reduceTransparency: false,
    reduceMotion: false,
    scrollState: 'idle',
    surfaces: [],
    ...over,
  };
}

export const stressed = { averageFrameTimeMs: 14, droppedFrameRatio: 0.3 };
